# Generated by Django 4.1.4 on 2022-12-24 10:33

from django.db import migrations
import main.validators
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='users/cover_photos/', validators=[main.validators.allow_only_images_validator], verbose_name='Cover_photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='users/profile_pictures/', validators=[main.validators.allow_only_images_validator], verbose_name='Profile_picture'),
        ),
    ]
