# Generated by Django 4.1.4 on 2022-12-27 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('latitude', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=128)),
                ('formatted', models.CharField(max_length=128)),
                ('country_code', models.CharField(max_length=128)),
                ('time_Zone', models.CharField(max_length=128)),
                ('currency_name', models.CharField(max_length=128)),
                ('location_type', models.CharField(max_length=128)),
                ('continent', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('county', models.CharField(max_length=128)),
                ('post_code', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('state_code', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('village', models.CharField(max_length=128)),
                ('road_info', models.CharField(max_length=128)),
                ('neighbourhood', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'visitor',
                'verbose_name_plural': 'visitors',
                'db_table': 'main_visitors',
                'ordering': ('-created_at', 'formatted'),
            },
        ),
    ]
