# Generated by Django 4.1.4 on 2022-12-24 10:01

from django.db import migrations
import main.validators
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_license',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='vendors/license/', validators=[main.validators.allow_only_images_validator], verbose_name='License_'),
        ),
    ]
