# Generated by Django 4.1.4 on 2022-12-24 13:37

from django.db import migrations
import main.validators
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_vendor_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_license',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='vendors/license/', validators=[main.validators.allow_only_images_validator], verbose_name='vendor_license'),
        ),
    ]
