# Generated by Django 4.1.5 on 2023-01-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_vendor_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(blank=True, max_length=128),
        ),
    ]
